### ISSUE TITLE
unicorn.sock failed : (No such file or directory) issue.

### ISSUE THREAD

**Issue by cusanelly** [ryuzee/SlideHub#107]
Hi ryuzee.
I'm trying to install your app on a AWS ubuntu 14.04 server.
I have followed all your instructions, however, i'm presenting an unicorn.sock error.
Here is the log message taken from slidehub_error.log:

2016/09/07 12:23:51 [crit] 1108#0: *12 connect() to unix:/tmp/unicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 190.7$

Unicorn.sock file is not on the /tmp folder,  i did like your opinion on this, so you can point me into the right track.

Please, let me know if you need anything else from me.
Thank you in advance and hope to hear from you soon.

**Comment by ryuzee** [comment]
@cusanelly It's difficult to identify the root cause of this error. However, it seems to show that unicorn was not running correctly. You can find a detailed log in ${ROOT}/log/production.log or ${ROOT}/log/unicorn.log.

I've just updated the installation procedure document for your help.
See https://github.com/ryuzee/SlideHub/commit/bfd765c43218a3f3b38ddec41e5f5473d75c5177

if you have any questions, please let me know.

**Comment by cusanelly** [comment]
Hi ryuzee.
Alright, i will follow the new instructions and let you know.
Thank you very much.

**Comment by cusanelly** [comment]
Hi ryuzee.
 Thank you very much, those modification help me a lot. Now i have a successful installation.
I just have something to add, at the running the application as a service section, on the code instruction, you named the service Unicorn, however, at the time to start the service, you were calling SlideHub instead of Unicorn, as you previously setup on the code.
You just have to modify that on your readme.md file.
Thank you very much for your help!.
Take care and good work.
